### ISSUE TITLE
Connect via Windows L2TP

### ISSUE THREAD

**Issue by dnwk** [philpl/setup-strong-strongswan#12]
I cannot connect via windows L2TP/IPsec VPN. Windows will gives 809 error.

Here are some syslog

Feb 11 15:10:05 access charon: 16[IKE] received 250000000 lifebytes, configured 0
Feb 11 15:10:05 access charon: 16[IKE] detected rekeying of CHILD_SA L2TP-IKEv1-PSK{10}
Feb 11 15:10:05 access charon: 16[ENC] generating QUICK_MODE response 4 [ HASH SA No ID ID NAT-OA NAT-OA ]
Feb 11 15:10:05 access charon: 07[ENC] parsed INFORMATIONAL_V1 request 2006123486 [ HASH D ]
Feb 11 15:10:05 access charon: 07[IKE] received DELETE for ESP CHILD_SA with SPI 6f60c2b3
Feb 11 15:10:05 access charon: 07[IKE] closing CHILD_SA L2TP-IKEv1-PSK{10} with SPIs cb3b79c2_i (0 bytes) 6f60c2b3_o (0 bytes) and TS 199.15._._/32[udp/l2f] === 74.85._._/32[udp/l2f]
Feb 11 15:10:05 access vpn: - 10.5.7.88 74.85._._ -- 199.15._._
Feb 11 15:10:05 access charon: 06[ENC] parsed QUICK_MODE request 4 [ HASH ]
Feb 11 15:10:05 access charon: 06[IKE] CHILD_SA L2TP-IKEv1-PSK{11} established with SPIs cfe46949_i 05c310d3_o and TS 199.15._._/32[udp/l2f] === 74.85._._/32[udp/l2f]
Feb 11 15:10:05 access vpn: + 10.5.7.88 74.85._._ -- 199.15._._

**Comment by philpl** [comment]
(sorry for responding this late)

I haven't got a Windows machine for reproducing this one. So it might take a while until I can try this.

this is a really short log. is this the entire thing? because there seems to be a lot missing.

Have you tried modifying the ipsec.conf according to this doc? https://wiki.strongswan.org/projects/strongswan/wiki/Win7SingleConfig

**Comment by freeyoung** [comment]
@dnwk Probably because your VPN server is also behind NAT.
