### ISSUE TITLE
Strongswan Ubuntu client setup !

### ISSUE THREAD

**Issue by gugansankar** [philpl/setup-strong-strongswan#22]
could you please provide a doc for how to setup strongswan vpn client on ubuntu desktop machine and connect to VPN server?.

**Comment by philpl** [comment]
No, the installation instructions must be enough, since I want to keep this basic. The information on how to connect will vary with the protocols / tunneling that you want to use, and your personal preferences. This is furthermore out of scop of the setup script.

You might want to check out network-manager-vpnc, if you don't know how to connect with an Ubuntu machine. http://packages.ubuntu.com/search?keywords=network-manager-vpnc
