### ISSUE TITLE
installation succesful, but unable to connect to server.

### ISSUE THREAD

**Issue by sz1805** [philpl/setup-strong-strongswan#37]
any idea?

**Comment by sz1805** [comment]
the previous installed pptp is not working after installation. how can i uninstall it from my server?

**Comment by sz1805** [comment]
it says No rule to make target 'uninstall' when make uninstall

**Comment by philpl** [comment]
PPTP is not supported by this setup. As it says in the readme, it only supports IPSec and IPSec&L2TP.

The uninstallation instructions are pretty clear:

> Download the Strongswan source and run: `make uninstall`
> Then uninstall `xl2tpd` and remove `/etc/init.d/vpn-assist`.

The Strongswan source are located here: https://download.strongswan.org/strongswan-5.5.1.tar.gz

Also, please don't add three comments and instead edit your old one, and try to provide more useful issue titles. In this case: `Can't connect via PPTP` would've been useful, since it immediately prompts me to reply to you, that PPTP is not supported.
