### ISSUE TITLE
error: OpenSSL libcrypto not found

### ISSUE THREAD

**Issue by T1MOXA** [philpl/setup-strong-strongswan#46]
When you install an error occurs:
OpenSSL libcrypto not found

**Comment by HerveH44** [comment]
Hi, it seems that i had the same problem when I installed on debian jessie. It seems that the script is wrong on line 238 : 
call pacapt -S --noconfirm -- make g++ gcc iptables xl2tpd libssl-dev module-init-tools curl openssl-devel

because openssl-devel doesn't seem to exist. So if you just delete the last bit "openssl-devel" from the line, it works just fine. 

OR you can install libssl-dev by yourself ( for me it was apt install libssl-dev)

Bye !

**Comment by abcfyk** [comment]
If you are using Debian/Ubuntu/Mint...etc with the apt tools, you can run this command below to install the necessary dependencies:
`apt-get install gcc libssl-dev xl2tpd strongswan-starter`
